<a href="https://colab.research.google.com/github/hyej987/TECHROSS/blob/master/Boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 패키지와 데이터 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import numpy as np

Mounted at /content/gdrive


In [4]:
data=pd.read_csv("/content/gdrive/MyDrive/테크로스/NEW_DB/predict_1.csv")

SECTION           START_TIME  OP_TYPE  OP_INDEX  FATAL_PERCENT  \
0           0  2020-07-09 02:09:36      1.0       2.0            0.0   
1           0  2020-07-09 02:14:04      1.0       3.0            0.0   
2           0  2020-07-09 02:18:53      1.0       4.0            0.0   
3           0  2020-07-09 02:35:39      1.0       5.0            0.0   
4           0  2020-07-09 03:03:53      1.0       7.0            0.0   
...       ...                  ...      ...       ...            ...   
6730        0  2021-12-31 08:58:08      2.0      40.0            0.0   
6731        0  2021-12-31 23:21:52      2.0      41.0            0.0   
6732        0  2022-01-04 08:20:07      1.0      97.0            0.0   
6733        0  2022-01-04 13:14:30      1.0      98.0            0.0   
6734        0  2022-01-05 12:19:37      1.0     101.0            0.0   

         pca_0     pca_1     pca_2     pca_3     pca_4     pca_5     pca_6  \
0    -0.300530 -0.105768 -0.184195  0.060466  0.177956 -0.058749 -0.374040   
1    -0.254178 -0.095446 -0.134511  0.047760  0.173309 -0.076288 -0.391673   
2    -0.238034 -0.092542 -0.119385  0.044032  0.172492 -0.081477 -0.399929   
3    -0.205302 -0.083773 -0.081439  0.033728  0.167564 -0.094631 -0.410720   
4    -0.304855 -0.106453 -0.183613  0.060755  0.177915 -0.061071 -0.366152   
...        ...       ...       ...       ...       ...       ...       ...   
6730 -0.369992  0.352785 -0.208245 -0.003594  0.069208 -0.016717  0.019806   
6731 -0.390527  0.378262 -0.198488  0.001742  0.022573  0.071373  0.010280   
6732 -0.098930  0.124305 -0.298860 -0.038465  0.020123 -0.045139  0.175654   
6733 -0.091662  0.131649 -0.307788 -0.038569  0.020682 -0.043666  0.180765   
6734 -0.014151  0.179546 -0.375882 -0.041552  0.021012 -0.021512  0.192099   

      TARGET  PREDICT  SHIP_ID  
0          0      0.0        1  
1          0      0.0        1  
2          0      0.0        1  
3          0      1.0        1  
4          0      0.0        1  
...      ...      ...      ...  
6730       0      0.0        0  
6731       0      1.0        0  
6732       0      0.0        0  
6733       0      0.0        0  
6734       0      0.0        0  

[6735 rows x 15 columns]

In [5]:
#data.drop(columns = ["Unnamed: 0"],inplace = True)
#data.drop(columns = ["date","FATAL_PERCENT","KEY","decision"],inplace = True)
data.drop(columns = ["START_TIME","TARGET","OP_INDEX","FATAL_PERCENT"],inplace = True)

In [6]:
data['PREDICT'].value_counts()

0.0    6466
1.0     269
Name: PREDICT, dtype: int64

In [ ]:
oversample = data[data['predict']=='NORMAL'].sample(frac = 10, replace = True)

In [ ]:
fatal_data = data[data['predict'] == "FATAL"]

In [ ]:
fatal_data = fatal_data.reset_index().drop(columns = ['index'])

In [ ]:
oversample = oversample.reset_index().drop(columns = ["index"])

In [ ]:
data=pd.concat([fatal_data, oversample])

In [ ]:
data['predict'].value_counts()

# X와 Y 나누기

In [8]:
X = data.drop(columns = ["PREDICT"])
y = data['PREDICT']
#y=y.replace({'NORMAL':0,'FATAL':1})
X

SECTION  OP_TYPE     pca_0     pca_1     pca_2     pca_3     pca_4  \
0           0      1.0 -0.300530 -0.105768 -0.184195  0.060466  0.177956   
1           0      1.0 -0.254178 -0.095446 -0.134511  0.047760  0.173309   
2           0      1.0 -0.238034 -0.092542 -0.119385  0.044032  0.172492   
3           0      1.0 -0.205302 -0.083773 -0.081439  0.033728  0.167564   
4           0      1.0 -0.304855 -0.106453 -0.183613  0.060755  0.177915   
...       ...      ...       ...       ...       ...       ...       ...   
6730        0      2.0 -0.369992  0.352785 -0.208245 -0.003594  0.069208   
6731        0      2.0 -0.390527  0.378262 -0.198488  0.001742  0.022573   
6732        0      1.0 -0.098930  0.124305 -0.298860 -0.038465  0.020123   
6733        0      1.0 -0.091662  0.131649 -0.307788 -0.038569  0.020682   
6734        0      1.0 -0.014151  0.179546 -0.375882 -0.041552  0.021012   

         pca_5     pca_6  SHIP_ID  
0    -0.058749 -0.374040        1  
1    -0.076288 -0.391673        1  
2    -0.081477 -0.399929        1  
3    -0.094631 -0.410720        1  
4    -0.061071 -0.366152        1  
...        ...       ...      ...  
6730 -0.016717  0.019806        0  
6731  0.071373  0.010280        0  
6732 -0.045139  0.175654        0  
6733 -0.043666  0.180765        0  
6734 -0.021512  0.192099        0  

[6735 rows x 10 columns]

# Train & TEST SPLIT

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify = y, train_size = 0.7 , random_state = 42)

# 스케일링

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler_X_train = MinMaxScaler()
scaler_X_train = scaler_X_train.fit(X_train)
X_train = scaler_X_train.transform(X_train)

In [ ]:
scaler_X_test = MinMaxScaler()
scaler_X_test = scaler_X_test.fit(X_test)
X_test = scaler_X_test.transform(X_test)

In [ ]:
print(X_train.shape)
print(X_test.shape)

# 앙상블 부스팅

- 여러 개의 약한 학습기를 순차적으로 학습시켜 예측하면서 잘 못 예측한 데이터에 가중치를 부여하여 오류를 개선해 나가며 학습하는 앙상블 모델
- 순차적 직렬 앙상블 방식
- GradientBoosting과 AdaBoosting이 있음

# 랜덤서치

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
param = {'n_estimators' : randint(low = 100, high = 1000),
         'max_features' : ['auto','sqrt','log2'],
         'max_depth' : [3]}
random_search = RandomizedSearchCV(GradientBoostingClassifier(),
                                   param_distributions=param,
                                   random_state = 42,
                                   n_iter=30,
                                   cv=4)
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=4, estimator=GradientBoostingClassifier(), n_iter=30,
                   param_distributions={'max_depth': [3],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f6c9327eb10>},
                   random_state=42)

In [ ]:
print("BEST Parameter: {}".format(random_search.best_params_))
print("Best Score: {:.4f}".format(random_search.best_score_))
print("TestSet Score: {:.4f}".format(random_search.score(X_test,y_test)))

BEST Parameter: {'max_depth': 3, 'max_features': 'auto', 'n_estimators': 918}
Best Score: 0.9539
TestSet Score: 0.6016


In [ ]:
pred_test = random_search.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_test = confusion_matrix(y_test,pred_test)
print(confusion_test)

[[388  28]
 [276  71]]


In [ ]:
print("normal 예측 : ", confusion_test[0,0]/sum(confusion_test[0]))
print("fatal 예측 : ", confusion_test[1,1]/sum(confusion_test[1]))

normal 예측 :  0.9326923076923077
fatal 예측 :  0.20461095100864554


In [ ]:
from sklearn.metrics import classification_report
report_test = classification_report(y_test,pred_test)
print("분류 예측 레포트:\n", report_test)

분류 예측 레포트:
               precision    recall  f1-score   support

           0       0.58      0.93      0.72       416
           1       0.72      0.20      0.32       347

    accuracy                           0.60       763
   macro avg       0.65      0.57      0.52       763
weighted avg       0.64      0.60      0.54       763



# 베이지안 옵티마이져

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
!pip install Bayesian-Optimization
from bayes_opt import BayesianOptimization
from scipy.stats import randint
from sklearn.metrics import make_scorer, precision_score
from sklearn.model_selection import cross_validate

def GradientBoostingClassifier_cv(learning_rate, max_depth ) : 
    model  = GradientBoostingClassifier(learning_rate = learning_rate,
                                        n_estimators = 1000,
                                        max_depth = int(round(max_depth)))
    scoring = {'precision_score' : make_scorer(precision_score)}
    result = cross_validate(model, X_train, y_train, cv = 5, scoring = scoring)
    auc_score = result["test_precision_score"].mean()
    return auc_score

pbounds = {'learning_rate' : (0.01,0.1),
           'max_depth' : (2,25)}

GradientBoostingClassifier_BO = BayesianOptimization(f=GradientBoostingClassifier_cv,pbounds = pbounds,verbose = 2,random_state = 42)


GradientBoostingClassifier_BO.maximize(init_points = 20,n_iter = 40)

GradientBoostingClassifier_BO.max

  Created wheel for Bayesian-Optimization: filename=bayesian_optimization-1.2.0-py3-none-any.whl size=11685 sha256=bbf0faf0ca78cb95d9c9b0f7c83415ba39c1f86e0dff19c89e8c95174bf07f7d
  Stored in directory: /root/.cache/pip/wheels/fd/9b/71/f127d694e02eb40bcf18c7ae9613b88a6be4470f57a8528c5b
Successfully built Bayesian-Optimization
|   iter    |  target   | learni... | max_depth |
-------------------------------------------------
|  1        |  0.1465   |  0.04371  |  23.87    |
|  2        |  0.1274   |  0.07588  |  15.77    |


In [ ]:
print("BEST Parameter: {}".format(random_search.best_params_))
print("Best Score: {:.4f}".format(random_search.best_score_))
print("TestSet Score: {:.4f}".format(random_search.score(X_test,y_test)))

BEST Parameter: {'max_depth': 3, 'max_features': 'sqrt', 'n_estimators': 121}
Best Score: 0.7026
TestSet Score: 0.6000


In [ ]:
pred_test = random_search.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_test = confusion_matrix(y_test,pred_test)
print(confusion_test)

[[241 108]
 [ 88  53]]


In [ ]:
print("normal 예측 : ", confusion_test[0,0]/sum(confusion_test[0]))
print("fatal 예측 : ", confusion_test[1,1]/sum(confusion_test[1]))

normal 예측 :  0.6905444126074498
fatal 예측 :  0.375886524822695


In [ ]:
from sklearn.metrics import classification_report
report_test = classification_report(y_test,pred_test)
print("분류 예측 레포트:\n", report_test)

분류 예측 레포트:
               precision    recall  f1-score   support

           0       0.73      0.69      0.71       349
           1       0.33      0.38      0.35       141

    accuracy                           0.60       490
   macro avg       0.53      0.53      0.53       490
weighted avg       0.62      0.60      0.61       490



# 최종 구현 모델

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(
    n_estimators = 1000,
    learning_rate = 0.02404,
    max_depth = 6,
    random_state = 42)

In [ ]:
model.fit(X_train, y_train)

NameError: ignored

In [ ]:
pred_train = model.predict(X_train)
model.score(X_train, y_train)

NameError: ignored

In [ ]:
pred_test = random_search.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_test = confusion_matrix(y_test,pred_test)
print(confusion_test)

[[388  28]
 [420  84]]


In [ ]:
print("normal 예측 : ", confusion_test[0,0]/sum(confusion_test[0]))
print("fatal 예측 : ", confusion_test[1,1]/sum(confusion_test[1]))

normal 예측 :  0.9326923076923077
fatal 예측 :  0.16666666666666666
